try {
    throw new ReferenceError("Hello");
  } catch (e) {
    console.log(e instanceof ReferenceError); // true
    console.log(e.message); // "Hello"
    console.log(e.name); // "ReferenceError"
    console.log(e.stack); // Stack of the error
  }